### ISSUE TITLE
[Arch] segfault when opening gui

### ISSUE THREAD

**Issue by 0xf0xx0** [tobimensch/aqemu#113]
I compiled `aqemu` without the `ppcemb` line (#92) and got through the setup before it suddenly segfaulted without a error. i ran it in `gdb` and got this:

```
(gdb) backtrace
#0  0x00007ffff6e3f111 in QWidget::raise() () at /usr/lib/libQt5Widgets.so.5
#1  0x00005555556c57e0 in Ui_Main_Window::setupUi(QMainWindow*)
    (this=0x555555b88ff0, Main_Window=0x555555b88fc0)
    at aqemu.p/ui_Main_Window.h:1017
#2  0x000055555569f705 in Main_Window::Main_Window(QWidget*)
    (this=0x555555b88fc0, parent=0x0) at ../src/Main_Window.cpp:77
#3  0x000055555569c280 in AQEMU_Main::main_window() (this=0x7fffffffddf0)
    at ../src/main.cpp:232
#4  0x000055555569bc01 in AQEMU_Main::main(int, char**)
    (this=0x7fffffffddf0, argc=1, argv=0x7fffffffdf28) at ../src/main.cpp:169
#5  0x000055555569f24f in main(int, char**) (argc=1, argv=0x7fffffffdf28)
    at ../src/main.cpp:522
```

#### Full backtrace
https://pastebin.com/6AkQcw55

**Comment by zen2** [comment]
I got accurately the same problem here with similar trace.

I try to debug this but it's not easy since I'm not a C++/QT dev.
I think this problem is related to these warnings:

```
# cmake -E cmake_autogen /root/aqemu/aqemu/CMakeFiles/aqemu_autogen.dir/AutogenInfo.json ""
AutoUic: /root/aqemu/aqemu/src/Advanced_Settings_Window.ui: Warning: The name 'widget' (QWidget) is already in use, defaulting to 'widget1'.
AutoUic: /root/aqemu/aqemu/src/Create_Template_Window.ui: Warning: The name 'groupBox' (QGroupBox) is already in use, defaulting to 'groupBox1'.
AutoUic: /root/aqemu/aqemu/src/Delete_VM_Files_Window.ui: Warning: Buddy assignment: '' is not a valid widget.
/root/aqemu/aqemu/src/Delete_VM_Files_Window.ui: Warning: Buddy assignment: '' is not a valid widget.
AutoUic: /root/aqemu/aqemu/src/Main_Window.ui: Warning: The name 'widget' (QWidget) is already in use, defaulting to 'widget1'.
/root/aqemu/aqemu/src/Main_Window.ui: Warning: The name 'widget' (QWidget) is already in use, defaulting to 'widget2'.
/root/aqemu/aqemu/src/Main_Window.ui: Warning: Z-order assignment: 'verticalSpacer_11' is not a valid widget.
/root/aqemu/aqemu/src/Main_Window.ui: Warning: Z-order assignment: 'verticalSpacer_5' is not a valid widget.
/root/aqemu/aqemu/src/Main_Window.ui: Warning: Z-order assignment: 'verticalSpacer_9' is not a valid widget.
/root/aqemu/aqemu/src/Main_Window.ui: Warning: Buddy assignment: '' is not a valid widget.
/root/aqemu/aqemu/src/Main_Window.ui: Warning: Buddy assignment: '' is not a valid widget.
AutoUic: /root/aqemu/aqemu/src/SPICE_Settings_Widget.ui: Warning: The name 'groupBox' (QGroupBox) is already in use, defaulting to 'groupBox1'.
/root/aqemu/aqemu/src/SPICE_Settings_Widget.ui: Warning: The name 'groupBox' (QGroupBox) is already in use, defaulting to 'groupBox2'.
```

**Comment by zen2** [comment]
> I got accurately the same problem here with similar trace.
> 
> I try to debug this but it's not easy since I'm not a C++/QT dev.
> I think this problem is related to these warnings:
> 
> ```
> # cmake -E cmake_autogen /root/aqemu/aqemu/CMakeFiles/aqemu_autogen.dir/AutogenInfo.json ""
> AutoUic: /root/aqemu/aqemu/src/Advanced_Settings_Window.ui: Warning: The name 'widget' (QWidget) is already in use, defaulting to 'widget1'.
> AutoUic: /root/aqemu/aqemu/src/Create_Template_Window.ui: Warning: The name 'groupBox' (QGroupBox) is already in use, defaulting to 'groupBox1'.
> AutoUic: /root/aqemu/aqemu/src/Delete_VM_Files_Window.ui: Warning: Buddy assignment: '' is not a valid widget.
> /root/aqemu/aqemu/src/Delete_VM_Files_Window.ui: Warning: Buddy assignment: '' is not a valid widget.
> AutoUic: /root/aqemu/aqemu/src/Main_Window.ui: Warning: The name 'widget' (QWidget) is already in use, defaulting to 'widget1'.
> /root/aqemu/aqemu/src/Main_Window.ui: Warning: The name 'widget' (QWidget) is already in use, defaulting to 'widget2'.
> /root/aqemu/aqemu/src/Main_Window.ui: Warning: Z-order assignment: 'verticalSpacer_11' is not a valid widget.
> /root/aqemu/aqemu/src/Main_Window.ui: Warning: Z-order assignment: 'verticalSpacer_5' is not a valid widget.
> /root/aqemu/aqemu/src/Main_Window.ui: Warning: Z-order assignment: 'verticalSpacer_9' is not a valid widget.
> /root/aqemu/aqemu/src/Main_Window.ui: Warning: Buddy assignment: '' is not a valid widget.
> /root/aqemu/aqemu/src/Main_Window.ui: Warning: Buddy assignment: '' is not a valid widget.
> AutoUic: /root/aqemu/aqemu/src/SPICE_Settings_Widget.ui: Warning: The name 'groupBox' (QGroupBox) is already in use, defaulting to 'groupBox1'.
> /root/aqemu/aqemu/src/SPICE_Settings_Widget.ui: Warning: The name 'groupBox' (QGroupBox) is already in use, defaulting to 'groupBox2'.
> ```

Finally it was a bad assumption. Everything seems correct in fact.

Here I got a working version if compiled in -j1 else that segfault.
But on another system. That don't work either with -j1 so it's confugsing.
