### ISSUE TITLE
Aqemu git crashes when going to VM / take screenshot options.

### ISSUE THREAD

**Issue by FredBezies** [tobimensch/aqemu#18]
I'm facing a weird bug. When I try to take a screenshot or to go to the qemu console with a git version of Aqemu (built against QT 5.7), it crashes.

I rebuilt Aqemu with debug symbols and here is the backtrace I got in gdb.

```
Thread 1 "aqemu" received signal SIGSEGV, Segmentation fault.
0x00000000007c1c3b in Virtual_Machine::Take_Screenshot (this=0x0, 
    file_name=..., width=-1, height=-1) at /home/fred/aqemu/src/VM.cpp:7334
7334		if( ! (State == VM::VMS_Running || State == VM::VMS_Pause) )
(gdb) bt
#0  0x00000000007c1c3b in Virtual_Machine::Take_Screenshot (this=0x0, 
    file_name=..., width=-1, height=-1) at /home/fred/aqemu/src/VM.cpp:7334
#1  0x0000000000680fea in Emulator_Control_Window::on_actionSave_Screenshot_triggered (this=0x1347580) at /home/fred/aqemu/src/Emulator_Control_Window.cpp:729
#2  0x000000000081806e in Emulator_Control_Window::qt_static_metacall (
    _o=0x1347580, _c=QMetaObject::InvokeMetaMethod, _id=10, _a=0x7fffffffd400)
    at /home/fred/aqemu/moc_Emulator_Control_Window.cpp:330
#3  0x00000000008185ec in Emulator_Control_Window::qt_metacall (
    this=0x1347580, _c=QMetaObject::InvokeMetaMethod, _id=10, 
    _a=0x7fffffffd400) at /home/fred/aqemu/moc_Emulator_Control_Window.cpp:436
#4  0x00007ffff5d61684 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#5  0x00007ffff6a0f472 in QAction::triggered(bool) ()
   from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff6a11e60 in QAction::activate(QAction::ActionEvent) ()
   from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff6b7feea in ?? () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff6b860ec in ?? () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff6b8a0e0 in QMenu::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff6a5cf18 in QWidget::event(QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff6b8ab9b in QMenu::event(QEvent*) ()
#12 0x00007ffff6a15e3c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff6a1e46d in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff5d35c80 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff6a1cb1d in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff6a775a0 in ?? () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff6a79763 in ?? () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff6a15e3c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff6a1d5b1 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff5d35c80 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/libQt5Core.so.5
#21 0x00007ffff62840e3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#22 0x00007ffff6285c65 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#23 0x00007ffff6263cbb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<#24 0x00007fffeab0c310 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#25 0x00007ffff1970dd7 in g_main_context_dispatch ()
   from /usr/lib/libglib-2.0.so.0
#26 0x00007ffff1971040 in ?? () from /usr/lib/libglib-2.0.so.0
#27 0x00007ffff19710ec in g_main_context_iteration ()
   from /usr/lib/libglib-2.0.so.0
#28 0x00007ffff5d8a57f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#29 0x00007ffff5d340da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#30 0x00007ffff5d3c5cc in QCoreApplication::exec() ()
   from /usr/lib/libQt5Core.so.5
#31 0x00000000006a864c in AQEMU_Main::main_window (this=0x7fffffffe7a0)
    at /home/fred/aqemu/src/main.cpp:237
#32 0x00000000006a7f4f in AQEMU_Main::main (this=0x7fffffffe7a0, argc=1, 
    argv=0x7fffffffe8c8) at /home/fred/aqemu/src/main.cpp:169
#33 0x00000000006ab7ea in main (argc=1, argv=0x7fffffffe8c8)
    at /home/fred/aqemu/src/main.cpp:522
```

I'm using Archlinux with gcc 6.1.1 and QT 5.7.0. I noticed Aqemu 0.9.2 doesn't crash.

Any ideas ?

**Comment by tobimensch** [comment]
git master isn't stable at the moment. There were a lot of changes under the hood since 0.9.2, and not every feature has been tested yet. Thanks for the report. I will make sure not to miss this bug when releasing 0.9.3.
